# application.yml
---
spring:
  application:
    name: masterpieces
server:
  port: 8081
masterpieces: Divina Commedia,Il fu Mattia Pascal,Cime tempestose,La coscienza di Zeno, La sonata a Kreutzer, Jurassic Park
